// flow-typed signature: 0b02c2c306ae8ffdf5eeb86a74bb95d3
// flow-typed version: <<STUB>>/@types/chai_v^4.0.10/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chai' {
  declare module.exports: any;
}
