// flow-typed signature: 76d54021cb31f065888a456883735071
// flow-typed version: <<STUB>>/@types/mocha_v^2.2.45/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
