// flow-typed signature: 3c13d31a02d1fe78f388acd10797c3bc
// flow-typed version: <<STUB>>/@types/mocha_v^2.2.45/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
