// flow-typed signature: 5547ac3c3bd68b140a9ecaed6cc48a46
// flow-typed version: <<STUB>>/types-dirty-chai_vgit+https://github.com/philgs/types-dirty-chai.git#development/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'types-dirty-chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'types-dirty-chai' {
  declare module.exports: any;
}
