// flow-typed signature: 3aeb39c230a734fb651ce98d880dc442
// flow-typed version: <<STUB>>/@philgs/spawn_v^1.0.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@philgs/spawn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@philgs/spawn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@philgs/spawn/index' {
  declare module.exports: $Exports<'@philgs/spawn'>;
}
declare module '@philgs/spawn/index.js' {
  declare module.exports: $Exports<'@philgs/spawn'>;
}
